modLoader="javafml"
loaderVersion="[40,)"
license="https://github.com/MasterGeneral156/CTD-Tweaks/blob/1.18/LICENSE"
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Tweaks/issues"

[[mods]]
modId="ctdtweaks"
version="2.1.4"
displayName="CTD Tweaks"
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/CTD-Tweaks.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ctd-tweaks"
logoFile="logo-new.png"
credits="TheMasterGeneral"
authors="TheMasterGeneral"
description='''
Misc tweaks, by TheMasterGeneral and friends.'''

[[dependencies.ctdtweaks]]
    modId="ctdcore"
    mandatory=true
    versionRange="[2.1.3,)"
	ordering="BEFORE"
    side="BOTH"
	
[[dependencies.ctdtweaks]]
    modId="curios"
    mandatory=true
    versionRange="[1.18.2-5.0.7,)"
	ordering="BEFORE"
    side="BOTH"
