modLoader="javafml" #mandatory
loaderVersion="[45,)" #mandatory
license="https://github.com/MasterGeneral156/CTD-Tweaks/blob/1.19/LICENSE"
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Tweaks/issues"

[[mods]] #mandatory
modId="ctdtweaks" #mandatory
version="2.3.0" #mandatory
displayName="CTD Tweaks" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/CTD-Tweaks.json" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/ctd-tweaks" 
logoFile="logo-new.png"
credits="TheMasterGeneral" 
authors="TheMasterGeneral"
description='''
Misc tweaks, by TheMasterGeneral and friends.'''

[[dependencies.ctdtweaks]] #optional
    modId="ctdcore" #mandatory
    mandatory=true #mandatory
    versionRange="[2.2,)" #mandatory
	ordering="BEFORE"
    side="BOTH"
	
[[dependencies.ctdtweaks]] #optional
    modId="curios" #mandatory
    mandatory=true #mandatory
    versionRange="[1.19.4-5.1,)" #mandatory
	ordering="BEFORE"
    side="BOTH"
