modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory
license="https://github.com/MasterGeneral156/CTD-Tweaks/blob/1.18/LICENSE"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="ctdtweaks" #mandatory
version="2.1.2" #mandatory
displayName="CTD Tweaks" #mandatory
updateJSONURL="https://raw.githubusercontent.com/MasterGeneral156/Version/master/CTD-Tweaks.json" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://www.curseforge.com/minecraft/mc-mods/ctd-tweaks" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="logo-new.png" #optional
# A text field displayed in the mod UI
credits="TheMasterGeneral" #optional
# A text field displayed in the mod UI
authors="" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Misc tweaks, by TheMasterGeneral and friends.'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.ctdtweaks]] #optional
    modId="ctdcore" #mandatory
    mandatory=true #mandatory
    versionRange="[2.1.2,)" #mandatory
	ordering="BEFORE"
    side="BOTH"
	
[[dependencies.ctdtweaks]] #optional
    modId="curios" #mandatory
    mandatory=true #mandatory
    versionRange="[1.18.2-5.0.7.1,)" #mandatory
	ordering="BEFORE"
    side="BOTH"
