modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"
issueTrackerURL="https://github.com/MasterGeneral156/CTD-Tweaks/issues" #optional

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ctd-tweaks"
logoFile="ctd-tweaks-logo.png"
authors="TheMasterGeneral"

description='''
Adds misc bits and bobs to the game.
'''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"


[[dependencies.${mod_id}]]
    modId="ctdcore"
    type="required"
    versionRange="[${ctd_core_ver},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="curios"
    type="required"
    versionRange="[${curios_version},)"
    ordering="NONE"
    side="BOTH"
